oklm_user:
    resource: "@OKLMUserBundle/Resources/config/routing.yml"
    prefix:   /

oklm_common:
    resource: "@OKLMCommonBundle/Resources/config/routing.yml"
    prefix:   /

oklm_app:
    resource: "@OKLMAppBundle/Resources/config/routing.yml"
    prefix:   /

